.phony all:
all: sfs

sfs:
	gcc -Wall diskinfo.c -o diskinfo
	gcc -Wall diskget.c -o diskget
	gcc -Wall diskput.c -o diskput

.PHONY clean:
clean:
	-rm -rf diskinfo
	-rm -rf diskget
	-rm -rf diskput







